CREATE TABLE IF NOT EXISTS reset_password (
  id TEXT PRIMARY KEY,
  token VARCHAR(255) NOT NULL UNIQUE,
  expires_in TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);